"""empty message

Revision ID: 0b06ae98b027
Revises: 56ea0b3e1cf9
Create Date: 2026-05-03 01:43:38.578835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b06ae98b027'
down_revision = '56ea0b3e1cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fab_style', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sys_factory', ['factory_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_category', ['category_id'], ['id'])

    with op.batch_alter_table('fab_style_elastic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'fab_style', ['style_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_size', ['size_id'], ['id'])

    with op.batch_alter_table('fab_style_price', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'fab_style', ['style_id'], ['id'])

    with op.batch_alter_table('fab_style_process', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'fab_style', ['style_id'], ['id'])

    with op.batch_alter_table('ord_order', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sys_factory', ['factory_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_user', ['customer_id'], ['id'])

    with op.batch_alter_table('ord_order_detail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'fab_style', ['style_id'], ['id'])
        batch_op.create_foreign_key(None, 'ord_order', ['order_id'], ['id'])

    with op.batch_alter_table('pro_style_process', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pro_process', ['process_id'], ['id'])
        batch_op.create_foreign_key(None, 'fab_style', ['style_id'], ['id'])

    with op.batch_alter_table('sys_reward_record', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sys_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_reward_config', ['reward_config_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_user', ['distributed_by'], ['id'])
        batch_op.create_foreign_key(None, 'sys_factory', ['factory_id'], ['id'])

    with op.batch_alter_table('sys_role_menu', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sys_menu', ['menu_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_role', ['role_id'], ['id'])

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sys_user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'sys_user', ['invited_by'], ['id'])

    with op.batch_alter_table('sys_user_factory', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sys_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_factory', ['factory_id'], ['id'])

    with op.batch_alter_table('sys_user_factory_role', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sys_role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_factory', ['factory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_user_factory_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sys_user_factory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sys_role_menu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sys_reward_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('pro_style_process', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ord_order_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ord_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('fab_style_process', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('fab_style_price', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('fab_style_elastic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('fab_style', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
