"""empty message

Revision ID: 56ea0b3e1cf9
Revises: d84a6d5dc238
Create Date: 2026-05-03 01:36:17.359773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56ea0b3e1cf9'
down_revision = 'd84a6d5dc238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pro_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='工序名称，如：裁剪、缝制、整烫'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='工序编码'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='工序描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1-启用，0-禁用'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='工序定义表'
    )
    op.create_table('sys_reward_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='奖励名称'),
    sa.Column('rule_type', sa.String(length=20), nullable=False, comment='规则类型：invite_count-邀请人数'),
    sa.Column('threshold', sa.Integer(), nullable=False, comment='触发阈值（如邀请满5人）'),
    sa.Column('reward_object', sa.String(length=20), nullable=False, comment='奖励对象：factory-工厂，personal-个人'),
    sa.Column('reward_type', sa.String(length=20), nullable=False, comment='奖励类型：extend-工厂VIP延期，cash-个人现金'),
    sa.Column('reward_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='奖励值（延期天数或现金金额）'),
    sa.Column('is_active', sa.SmallInteger(), nullable=True, comment='是否启用：1-启用，0-禁用'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_type', 'threshold', 'reward_object', 'is_deleted', name='uk_rule_type_threshold_object'),
    comment='奖励配置表，支持动态配置奖励规则'
    )
    op.create_table('ord_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='订单号'),
    sa.Column('factory_id', sa.Integer(), nullable=False, comment='工厂ID'),
    sa.Column('customer_id', sa.Integer(), nullable=True, comment='客户ID'),
    sa.Column('customer_name', sa.String(length=100), nullable=True, comment='客户名称'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='订单日期'),
    sa.Column('delivery_date', sa.Date(), nullable=True, comment='交货日期'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='订单状态：pending-待确认，confirmed-已确认，processing-生产中，completed-已完成，cancelled-已取消'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='订单总金额'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('create_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('update_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['customer_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['sys_factory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no'),
    comment='订单主表'
    )
    with op.batch_alter_table('ord_order', schema=None) as batch_op:
        batch_op.create_index('idx_factory_id', ['factory_id'], unique=False)
        batch_op.create_index('idx_order_date', ['order_date'], unique=False)
        batch_op.create_index('idx_order_no', ['order_no'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)

    op.create_table('sys_reward_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reward_object', sa.String(length=20), nullable=False, comment='奖励对象：factory-工厂，personal-个人'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID（关联触发人）'),
    sa.Column('factory_id', sa.Integer(), nullable=True, comment='工厂ID（奖励工厂时必填）'),
    sa.Column('reward_config_id', sa.Integer(), nullable=True, comment='奖励配置ID'),
    sa.Column('reward_type', sa.String(length=20), nullable=False, comment='奖励类型：extend-工厂VIP延期，cash-个人现金'),
    sa.Column('reward_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='奖励值'),
    sa.Column('trigger_condition', sa.String(length=100), nullable=True, comment='触发条件'),
    sa.Column('trigger_value', sa.Integer(), nullable=True, comment='触发时的数值'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending-待发放，distributed-已发放，cancelled-已取消'),
    sa.Column('distributed_by', sa.Integer(), nullable=True, comment='发放人ID'),
    sa.Column('distributed_time', sa.DateTime(), nullable=True, comment='发放时间'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['distributed_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['sys_factory.id'], ),
    sa.ForeignKeyConstraint(['reward_config_id'], ['sys_reward_config.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='奖励记录表'
    )
    with op.batch_alter_table('sys_reward_record', schema=None) as batch_op:
        batch_op.create_index('idx_factory_id', ['factory_id'], unique=False)
        batch_op.create_index('idx_reward_object', ['reward_object'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)

    op.create_table('ord_order_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='订单ID'),
    sa.Column('style_id', sa.Integer(), nullable=False, comment='款号ID'),
    sa.Column('style_no', sa.String(length=50), nullable=True, comment='款号'),
    sa.Column('style_name', sa.String(length=100), nullable=True, comment='款号名称'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='单价'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='小计金额'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['order_id'], ['ord_order.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['fab_style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='订单明细表'
    )
    with op.batch_alter_table('ord_order_detail', schema=None) as batch_op:
        batch_op.create_index('idx_order_id', ['order_id'], unique=False)
        batch_op.create_index('idx_style_id', ['style_id'], unique=False)

    op.create_table('pro_style_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False, comment='款号ID'),
    sa.Column('process_id', sa.Integer(), nullable=False, comment='工序ID'),
    sa.Column('sequence', sa.Integer(), nullable=True, comment='工序顺序（第几道工序）'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['process_id'], ['pro_process.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['fab_style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'process_id', name='uk_style_process'),
    comment='款号工序关联表'
    )
    with op.batch_alter_table('pro_style_process', schema=None) as batch_op:
        batch_op.create_index('idx_style_id', ['style_id'], unique=False)

    op.drop_table('fab_style_splice')
    with op.batch_alter_table('fab_style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_splice', sa.SmallInteger(), nullable=True, comment='是否拼接款：0-否，1-是'))
        batch_op.add_column(sa.Column('splice_data', sa.JSON(), nullable=True, comment='拼接数据，格式：[{"sequence":1,"description":"红色棉麻"},{"sequence":2,"description":"绿色梭织"}]'))
        batch_op.create_foreign_key(None, 'sys_factory', ['factory_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_category', ['category_id'], ['id'])

    with op.batch_alter_table('fab_style_elastic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sys_size', ['size_id'], ['id'])
        batch_op.create_foreign_key(None, 'fab_style', ['style_id'], ['id'])

    with op.batch_alter_table('fab_style_price', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'fab_style', ['style_id'], ['id'])

    with op.batch_alter_table('fab_style_process', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'fab_style', ['style_id'], ['id'])

    with op.batch_alter_table('sys_factory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qrcode', sa.String(length=500), nullable=True, comment='工厂二维码URL，扫码可绑定工厂'))
        batch_op.add_column(sa.Column('qrcode_key', sa.String(length=100), nullable=True, comment='二维码唯一标识，用于扫码绑定'))
        batch_op.add_column(sa.Column('vip_expire_date', sa.Date(), nullable=True, comment='工厂VIP到期日期'))
        batch_op.create_unique_constraint(None, ['qrcode_key'])

    with op.batch_alter_table('sys_role', schema=None) as batch_op:
        batch_op.alter_column('factory_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='0表示平台级角色，>0表示工厂角色')
        batch_op.alter_column('status',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='状态：1-启用，0-禁用',
               existing_comment='状态：1启用 0禁用',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('uk_factory_role_name'))
        batch_op.drop_constraint(batch_op.f('uk_factory_role_code'), type_='unique')
        batch_op.create_unique_constraint('uk_factory_role_code', ['factory_id', 'code', 'is_deleted'])
        batch_op.drop_table_comment(
        existing_comment='角色表'
    )
        batch_op.drop_column('remark')

    with op.batch_alter_table('sys_role_menu', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='角色id',
               existing_nullable=False)
        batch_op.alter_column('menu_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='菜单/权限id',
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'sys_role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_menu', ['menu_id'], ['id'])

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=20), nullable=True, comment='用户邀请码（唯一）'))
        batch_op.add_column(sa.Column('invited_by', sa.Integer(), nullable=True, comment='邀请人用户ID'))
        batch_op.add_column(sa.Column('invited_count', sa.Integer(), nullable=True, comment='成功邀请人数'))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人用户ID'))
        batch_op.create_unique_constraint(None, ['invite_code'])
        batch_op.create_foreign_key(None, 'sys_user', ['invited_by'], ['id'])
        batch_op.create_foreign_key(None, 'sys_user', ['created_by'], ['id'])

    with op.batch_alter_table('sys_user_factory', schema=None) as batch_op:
        batch_op.alter_column('relation_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='关系类型：owner-工厂主体账号，employee-员工，customer-客户，collaborator-协作用户',
               existing_comment='关系类型：employee-员工，customer-客户，collaborator-协作用户',
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'sys_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_factory', ['factory_id'], ['id'])

    with op.batch_alter_table('sys_user_factory_role', schema=None) as batch_op:
        batch_op.alter_column('factory_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='工厂ID（平台角色时可为0）',
               existing_comment='工厂ID',
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'sys_role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'sys_factory', ['factory_id'], ['id'])
        batch_op.create_table_comment(
        '用户-工厂-角色关联表',
        existing_comment='用户-工厂-角色关联表，记录用户在指定工厂的角色'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_user_factory_role', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户-工厂-角色关联表，记录用户在指定工厂的角色',
        existing_comment='用户-工厂-角色关联表'
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('factory_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='工厂ID',
               existing_comment='工厂ID（平台角色时可为0）',
               existing_nullable=False)

    with op.batch_alter_table('sys_user_factory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('relation_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='关系类型：employee-员工，customer-客户，collaborator-协作用户',
               existing_comment='关系类型：owner-工厂主体账号，employee-员工，customer-客户，collaborator-协作用户',
               existing_nullable=False)

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_by')
        batch_op.drop_column('invited_count')
        batch_op.drop_column('invited_by')
        batch_op.drop_column('invite_code')

    with op.batch_alter_table('sys_role_menu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('menu_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='菜单/权限id',
               existing_nullable=False)
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='角色id',
               existing_nullable=False)

    with op.batch_alter_table('sys_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='备注'))
        batch_op.create_table_comment(
        '角色表',
        existing_comment=None
    )
        batch_op.drop_constraint('uk_factory_role_code', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uk_factory_role_code'), ['factory_id', 'code'])
        batch_op.create_index(batch_op.f('uk_factory_role_name'), ['factory_id', 'name'], unique=True)
        batch_op.alter_column('status',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='状态：1启用 0禁用',
               existing_comment='状态：1-启用，0-禁用',
               existing_nullable=True)
        batch_op.alter_column('factory_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='0表示平台级角色，>0表示工厂角色')

    with op.batch_alter_table('sys_factory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('vip_expire_date')
        batch_op.drop_column('qrcode_key')
        batch_op.drop_column('qrcode')

    with op.batch_alter_table('fab_style_process', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('fab_style_price', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('fab_style_elastic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('fab_style', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('splice_data')
        batch_op.drop_column('is_splice')

    op.create_table('fab_style_splice',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('style_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='款号ID'),
    sa.Column('splice_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='拼接类型：color-颜色拼接，fabric-布料拼接，lace-蕾丝拼接，other-其他'),
    sa.Column('material_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='材料ID（颜色ID或布料ID）'),
    sa.Column('material_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='材料名称'),
    sa.Column('material_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='材料编码'),
    sa.Column('sort_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='款号拼接明细表，记录颜色拼接、布料拼接等拼接信息',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='款号拼接明细表，记录颜色拼接、布料拼接等拼接信息',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('pro_style_process', schema=None) as batch_op:
        batch_op.drop_index('idx_style_id')

    op.drop_table('pro_style_process')
    with op.batch_alter_table('ord_order_detail', schema=None) as batch_op:
        batch_op.drop_index('idx_style_id')
        batch_op.drop_index('idx_order_id')

    op.drop_table('ord_order_detail')
    with op.batch_alter_table('sys_reward_record', schema=None) as batch_op:
        batch_op.drop_index('idx_user_id')
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_reward_object')
        batch_op.drop_index('idx_factory_id')

    op.drop_table('sys_reward_record')
    with op.batch_alter_table('ord_order', schema=None) as batch_op:
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_order_no')
        batch_op.drop_index('idx_order_date')
        batch_op.drop_index('idx_factory_id')

    op.drop_table('ord_order')
    op.drop_table('sys_reward_config')
    op.drop_table('pro_process')
    # ### end Alembic commands ###
