"""empty message

Revision ID: d84a6d5dc238
Revises: 
Create Date: 2026-04-21 01:14:35.262709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84a6d5dc238'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fab_color',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='颜色名称，工厂内叫法，如：子色'),
    sa.Column('actual_name', sa.String(length=50), nullable=False, comment='实际颜色名称，布料上标准名称，如：紫色'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='颜色编码，工厂内唯一，如：PURPLE01'),
    sa.Column('factory_id', sa.Integer(), nullable=True, comment='所属工厂ID，0为全局默认，大于0为工厂自定义'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序，数字越小越靠前'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1-启用，0-禁用'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'code', 'is_deleted', name='uk_factory_color_code'),
    comment='颜色表，存储布料颜色，支持工厂内叫法和实际名称对照'
    )
    op.create_table('sys_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称，如：上衣、裤子、裙子、外套'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID，0为顶级分类'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='分类编码，如：TOP、PANTS、SKIRT'),
    sa.Column('factory_id', sa.Integer(), nullable=True, comment='所属工厂ID，0为全局默认，大于0为工厂自定义'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序，数字越小越靠前'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1-启用，0-禁用'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'code', 'is_deleted', name='uk_factory_category_code'),
    comment='分类表，存储系统默认分类和工厂自定义分类，支持多级分类'
    )
    op.create_table('sys_factory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='工厂名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='工厂编码'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1启用 0禁用'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='工厂表'
    )
    op.create_table('sys_login_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('login_type', sa.String(length=20), nullable=True, comment='登录类型：pc/miniapp'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1成功 0失败'),
    sa.Column('error_msg', sa.String(length=255), nullable=True, comment='错误信息'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='登录时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录日志表'
    )
    op.create_table('sys_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='菜单名称'),
    sa.Column('path', sa.String(length=100), nullable=True, comment='路由路径'),
    sa.Column('component', sa.String(length=100), nullable=True, comment='组件路径'),
    sa.Column('permission', sa.String(length=100), nullable=True, comment='权限标识'),
    sa.Column('type', sa.SmallInteger(), nullable=True, comment='类型：0目录 1菜单 2按钮'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1启用 0禁用'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单/权限表'
    )
    op.create_table('sys_operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='操作用户名'),
    sa.Column('factory_id', sa.Integer(), nullable=True, comment='所属工厂ID'),
    sa.Column('operation', sa.String(length=255), nullable=True, comment='操作描述'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='请求方法'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='请求URL'),
    sa.Column('params', sa.Text(), nullable=True, comment='请求参数'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='执行耗时(ms)'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1成功 0失败'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='操作日志表'
    )
    op.create_table('sys_size',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='尺码名称，如：S、M、L、XL、XXL'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='尺码编码，如：S、M、L、XL、XXL'),
    sa.Column('factory_id', sa.Integer(), nullable=True, comment='所属工厂ID，0为全局默认，大于0为工厂自定义'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序，数字越小越靠前'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1-启用，0-禁用'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'code', 'is_deleted', name='uk_factory_size_code'),
    comment='尺码表，存储系统默认尺码和工厂自定义尺码'
    )
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('openid', sa.String(length=100), nullable=True, comment='微信openid'),
    sa.Column('is_admin', sa.SmallInteger(), nullable=True, comment='是否公司内部人员：1-是，0-否'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='账号状态：1-正常，0-禁用'),
    sa.Column('last_login_time', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fab_style',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False, comment='所属工厂ID'),
    sa.Column('style_no', sa.String(length=50), nullable=False, comment='款号，工厂内唯一，如：6032#'),
    sa.Column('customer_style_no', sa.String(length=50), nullable=True, comment='客户款号，客户提供的款号编码'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='款号名称，产品名称，如：圆领印花T恤'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID，关联分类表'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='适用性别：男/女/通用'),
    sa.Column('season', sa.String(length=10), nullable=True, comment='适用季节：春/夏/秋/冬/四季'),
    sa.Column('material', sa.String(length=200), nullable=True, comment='材质成分，如：95%棉 5%氨纶'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1-启用，0-禁用'),
    sa.Column('images', sa.JSON(), nullable=True, comment='产品图片URL列表，JSON数组格式'),
    sa.Column('need_cutting', sa.SmallInteger(), nullable=True, comment='是否需要切捆条：1-是，0-否'),
    sa.Column('cutting_reserve', sa.Numeric(precision=10, scale=2), nullable=True, comment='捆条预留长度(厘米)，每件预留多少cm'),
    sa.Column('custom_attributes', sa.JSON(), nullable=True, comment='自定义属性，JSON格式，如：{"属性名":"属性值"}'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['sys_category.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['sys_factory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'style_no', 'is_deleted', name='uk_factory_style_no'),
    comment='款号主表，存储款号基础信息、生产属性等'
    )
    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False, comment='所属工厂ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1启用 0禁用'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['factory_id'], ['sys_factory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'code', name='uk_factory_role_code'),
    sa.UniqueConstraint('factory_id', 'name', name='uk_factory_role_name'),
    comment='角色表'
    )
    op.create_table('sys_user_factory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('factory_id', sa.Integer(), nullable=False, comment='工厂ID'),
    sa.Column('relation_type', sa.String(length=20), nullable=False, comment='关系类型：employee-员工，customer-客户，collaborator-协作用户'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='关联状态：1-在职/有效，0-离职/无效'),
    sa.Column('entry_date', sa.Date(), nullable=True, comment='入职日期/关联日期'),
    sa.Column('leave_date', sa.Date(), nullable=True, comment='离职日期/解除日期'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['factory_id'], ['sys_factory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'factory_id', 'relation_type', name='uk_user_factory_relation'),
    comment='用户-工厂关联表，记录用户与工厂的关系类型'
    )
    op.create_table('fab_style_elastic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False, comment='款号ID'),
    sa.Column('size_id', sa.Integer(), nullable=True, comment='尺码ID，可为空表示所有尺码'),
    sa.Column('elastic_type', sa.String(length=50), nullable=False, comment='橡筋种类，如：2cm宽橡筋、3cm宽橡筋'),
    sa.Column('elastic_length', sa.Numeric(precision=10, scale=2), nullable=False, comment='橡筋长度(厘米)'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='数量，如需要几条橡筋'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['size_id'], ['sys_size.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['fab_style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='款号橡筋明细表，记录不同尺码所需的不同橡筋'
    )
    op.create_table('fab_style_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False, comment='款号ID'),
    sa.Column('price_type', sa.String(length=20), nullable=False, comment='价格类型：customer-客户价，internal-内部价，outsourced-外发价，button-钉扣价，other-其他'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='价格'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='生效日期'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['style_id'], ['fab_style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='款号价格表，记录各种价格类型及历史变动'
    )
    op.create_table('fab_style_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False, comment='款号ID'),
    sa.Column('process_type', sa.String(length=20), nullable=False, comment='工艺类型：embroidery-刺绣，print-印花，other-其他'),
    sa.Column('process_name', sa.String(length=50), nullable=True, comment='工艺名称，如：电脑刺绣、丝网印花'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['style_id'], ['fab_style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='款号工艺表，记录刺绣、印花等特殊工艺'
    )
    op.create_table('fab_style_splice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False, comment='款号ID'),
    sa.Column('splice_type', sa.String(length=20), nullable=False, comment='拼接类型：color-颜色拼接，fabric-布料拼接，lace-蕾丝拼接，other-其他'),
    sa.Column('material_id', sa.Integer(), nullable=True, comment='材料ID（颜色ID或布料ID）'),
    sa.Column('material_name', sa.String(length=100), nullable=True, comment='材料名称'),
    sa.Column('material_code', sa.String(length=50), nullable=True, comment='材料编码'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除：0-未删除，1-已删除'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['style_id'], ['fab_style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='款号拼接明细表，记录颜色拼接、布料拼接等拼接信息'
    )
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色id'),
    sa.Column('menu_id', sa.Integer(), nullable=False, comment='菜单/权限id'),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('sys_user_factory_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('factory_id', sa.Integer(), nullable=False, comment='工厂ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['factory_id'], ['sys_factory.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'factory_id', 'role_id', name='uk_user_factory_role'),
    comment='用户-工厂-角色关联表，记录用户在指定工厂的角色'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_factory_role')
    op.drop_table('sys_role_menu')
    op.drop_table('fab_style_splice')
    op.drop_table('fab_style_process')
    op.drop_table('fab_style_price')
    op.drop_table('fab_style_elastic')
    op.drop_table('sys_user_factory')
    op.drop_table('sys_role')
    op.drop_table('fab_style')
    op.drop_table('sys_user')
    op.drop_table('sys_size')
    op.drop_table('sys_operation_log')
    op.drop_table('sys_menu')
    op.drop_table('sys_login_log')
    op.drop_table('sys_factory')
    op.drop_table('sys_category')
    op.drop_table('fab_color')
    # ### end Alembic commands ###
