name: Deploy ZGF ERP

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "开始进入项目目录..."
            cd /root/ZGF_erp
            
            echo "正在从 GitHub 拉取最新代码..."
            # 1. 配置 Git 凭据，使用 GITHUB_TOKEN 进行免密拉取
            # git config --global credential.helper store
            # echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" > ~/.git-credentials
            
            # 2. 拉取 main 分支的最新代码
            git pull origin master
            
            echo "进入虚拟环境并安装依赖..."
            source /root/ZGF_erp/venv/bin/activate
            pip install -r requirements.txt
            
            echo "重启系统服务..."
            sudo systemctl restart zgf_erp.service
            
            echo "部署完成！"
